### ISSUE TITLE
FEATURE REQUEST | Add support for "include" option in config file

### ISSUE THREAD

**Issue by tahacodes** [braedon/prometheus-es-exporter#103]
Hi, I've started using this project in production and everything seems to be working well so far, but the problem is i want to generate a log of metrics from my nginx access logs, so i'm using this project to fetch them by querying Elasticsearch, and so far, my configuration file is over 1000 lines and it's getting so hard to maintain.

It would be perfect if we could use something like "**include usr/src/app/config.d/***" in the configuration file, so we could seprate every query section into multiple files.

**Comment by braedon** [comment]
Hi @tahacodes, you can use a folder containing multiple query config files, with the `--config-dir` option (https://github.com/braedon/prometheus-es-exporter/blob/7ae9a42f447f0000363d53dacb99262348c91425/prometheus_es_exporter/__init__.py#L448-L455).

Does that not satisfy your use case?
