### ISSUE TITLE
Does it support Elastic Search Open Distro

### ISSUE THREAD

**Issue by BhusanBibhuti** [braedon/prometheus-es-exporter#106]
Does ES Open Distro (https://www.elastic.co/downloads/past-releases/elasticsearch-oss-7-10-2) supports this exporter ??

**Comment by braedon** [comment]
Yes, this exporter supports Elasticsearch 7.10.2.

**Comment by BhusanBibhuti** [comment]
Please note that I did mention ES **OSS** 7.10.2 , not ES 7.10.2

**Comment by braedon** [comment]
Whether it the OSS version or otherwise has no bearing on the operation of exporter, so long as the cluster is functional and the exporter can access it.

If you have any concerns, I suggest you try it.
