### ISSUE TITLE
No way to get per-node index stats

### ISSUE THREAD

**Issue by atombender** [braedon/prometheus-es-exporter#22]
`es_indices_stats_primaries_docs_count` contains aggregated stats for the entire cluster. But there's no corresponding per-node index data, even though the code looks like it's supposed to default to getting everything from `/_nodes/stats`. For example:

```
$ curl -s http://10.4.14.73:9206/metrics | grep es_nodes | grep indic | wc -l
0
```

[Here](https://gist.github.com/atombender/67dab3ce52d04ab8830bb55fb3945556) is the complete output. My flags (in Kubernetes format):

```
        args:
        - --query-disable
        - --cluster-health-timeout
        - "30"
        - --nodes-stats-timeout
        - "30"
        - --indices-stats-timeout
        - "30"
        - --indices-stats-mode
        - indices
        - -e
        - localhost:9200
```

Not getting any different if I try to force it with `--nodes-stats-metrics indices`.

Edit: I see that the code explicitly drops this information:

```python
excluded_keys = [
    'timestamp',
    'indices',
]
```

Is there any reason why?

**Comment by braedon** [comment]
Hi @atombender,

The `--indices-stats-mode` flag only affects the metrics parsed from `/_stats`(`es_indices_stats_*`), not `/_nodes/stats`(`es_nodes_stats_*`).

The various ES metric endpoints contain some overlapping information, so I probably excluded the `indices` section of `/_nodes/stats` on the assumption that the more detailed information available in `/_stats` would suffice. However, looking at it again, you're right that you can't get/construct index stats aggregated to a node from any existing metrics.

I've pushed release [0.4.3](https://github.com/braedon/prometheus-es-exporter/releases/tag/0.4.3) with a fix for this. Hopefully that gets you the metrics you need!

Braedon

**Comment by atombender** [comment]
Awesome, thanks.
