### ISSUE TITLE
Name of indices with incrementing IDs

### ISSUE THREAD

**Issue by jangrewe** [braedon/prometheus-es-exporter#24]
Hi, i'd like to not query all indexes to keep the load reasonable, but unfortunately we're not using date-based index names, but rather incrementing IDs.
Is there any way to do something like `QueryIndices = <myIndex_{highest_id}>`?

**Comment by braedon** [comment]
Hi @jangrewe,

It doesn't look like there's any support for this kind of index naming scheme in Elasticsearch itself, so it'd be fairly substantial to implement. I'll have a think about a generic way to do this, and if it makes sense to support the feature.

It won't be until next year though, if it happens.

Regards,
Braedon

**Comment by DeviaVir** [comment]
For those running into this now:
```
  cat <<- 'EOF' > /home/bs/prometheus/es.cfg.template
[DEFAULT]
# How often to run queries.
QueryIntervalSecs = 15
# How long to wait for a query to return before timing out.
QueryTimeoutSecs = 10
# The indices to run the query on.
# Any way of specifying indices supported by your Elasticsearch version can be used.
QueryIndices = _all

[query_liquid_v1_tips]
QueryIntervalSecs = 15
QueryTimeoutSecs = 10
QueryIndices = syslog-ng_{YEAR}.{MONTH}.{DAY}
QueryJson = {
        "size": 0,
        "query": {
          "dis_max": {
            "queries": [
              { "match": { "HOST": "*" }},
              { "match": { "MESSAGE": "*" }}
            ]
          }
        }
    }
EOF

  cat <<- 'EOF' > /home/bs/prometheus/es.cfg.sh
#!/bin/bash

YEAR=$(date +%Y)
MONTH=$(date +%m)
DAY=$(date +%d)

cp -f /home/bs/prometheus/es.cfg.template /home/bs/prometheus/es.cfg

sed -i "s~{YEAR}~${YEAR}~g" /home/bs/prometheus/es.cfg
sed -i "s~{MONTH}~${MONTH}~g" /home/bs/prometheus/es.cfg
sed -i "s~{DAY}~${DAY}~g" /home/bs/prometheus/es.cfg
EOF

  chmod +x /home/bs/prometheus/es.cfg.sh
```

Then you can use the following line in your systemd service:
`ExecStartPre=/bin/bash /home/bs/prometheus/es.cfg.sh`

and have another timer service automatically restart your service daily or hourly:
```
  cat <<- 'EOF' > /etc/systemd/system/restart_prometheus_es_exporter.service
[Unit]
Description=Restart prometheus_es_exporter service

[Service]
Type=oneshot
ExecStart=/bin/systemctl try-restart prometheus_es_exporter.service
EOF

  cat <<- 'EOF' > /etc/systemd/system/restart_prometheus_es_exporter.timer
[Unit]
Description=Restart prometheus_es_exporter service every hour

[Timer]
OnCalendar=*-*-* *:00:00
Persistent=true

[Install]
WantedBy=timers.target
EOF
```

**Comment by jangrewe** [comment]
Haha, nice workaround! ;-)

I actually figured out that i can just use `graylog_deflector` (as we're using Graylog), which is an alias to the currently active (real) index.

**Comment by DeviaVir** [comment]
@jangrewe huh. That would be handy, but I don't think syslog has an alias (at least, I couldn't find any).

**Comment by jangrewe** [comment]
@DeviaVir I'm just wondering why you're doing it that complicated, instead of using the Date math as provided by the example config?
```
QueryIndices = <logstash-{now/d}>
```
Which would result in `logstash-2018.12.06` for today (as explained [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html)).

This issue was about indices which _don't_ use the date.

**Comment by DeviaVir** [comment]
:man_facepalming: 

Yep, ignore all of the above. I thought `{now/d}` was just to get the *day*, so it kept failing for me.

Thank you for pointing this out! _cleans up all the added bloat_

**Comment by wwlooi** [comment]
I created a sample Config for the exporter

`apiVersion: v1
kind: ConfigMap
metadata:
  name: es-exporter-config
  namespace: monitoring
data:
  exporter.cfg: |
    [DEFAULT]
    QueryIntervalSecs = 60
    QueryTimeoutSecs = 10
    #QueryIndices = _all
    QueryIndices = audit_logs_20190701
   
    # anything after the first query_ is used for the metric name
    [query_es_query_test]
    #QueryIndices = "stage-us-east-1-eks-2019.07.31"
    QueryJson = {
            "query": {
               "match_all": {}
            }
          }

    scrape_configs:
      metric_relabel_configs:
      - source_labels: [ __name__ ]
        regex: '(es_query_test(.+)'
        replacement: es_$1
        target_label: __name__`

But I only received metrics from  _cluster, _nodes and _stats so far, nothing from audit_logs_20190701. I also tried "QueryIndices = _all", the results were the same. Can anyone pls help pin point what I have done incorrectly?

Thank you.

**Comment by braedon** [comment]
@wwlooi Please open a separate issue - this issue is an unrelated enhancement request.

**Comment by RobertKirk** [comment]
Elasticsearch has index aliases which you can set up, and then point this exporter at the alias. See https://www.elastic.co/guide/en/elasticsearch/reference/7.7/indices-aliases.html 

They can also be managed automatically if you're using index lifecycle management: https://www.elastic.co/guide/en/elasticsearch/reference/current/overview-index-lifecycle-management.html

**Comment by braedon** [comment]
I'm going to close this, since @RobertKirk's [solution above](https://github.com/braedon/prometheus-es-exporter/issues/24#issuecomment-624510361) seems like the best option for handling these types of indices.

If anyone has an idea for how to support this natively in the exporter, feel free to re-open to discuss.
