### ISSUE TITLE
Invalid metric name

### ISSUE THREAD

**Issue by daveres** [Braedon/prometheus-es-exporter#3]
If you configure a percentile query to Elasticsearch, you receive the following error (Invalid metric name):

Traceback (most recent call last):
  File "./prometheus-es-exporter", line 11, in <module>
    sys.exit(main())
  File "/home/logiadmin/.local/lib/python3.5/site-packages/prometheus_es_exporter/__init__.py", line 135, in main
    scheduler.run()
  File "/usr/lib/python3.5/sched.py", line 147, in run
    action(*argument, **kwargs)
  File "/home/logiadmin/.local/lib/python3.5/site-packages/prometheus_es_exporter/__init__.py", line 65, in scheduled_run
    update_gauges(metrics)
  File "/home/logiadmin/.local/lib/python3.5/site-packages/prometheus_es_exporter/__init__.py", line 41, in update_gauges
    gauge = Gauge(metric_name, '', label_keys)
  File "/home/logiadmin/.local/lib/python3.5/site-packages/prometheus_client/core.py", line 333, in init
    raise ValueError('Invalid metric name: ' + full_name)
ValueError: Invalid metric name: homemvc_perc_values_50.0

I have reviewed the prometheus_client project and I see that Prometheus can't create a metric with "." in its name.

**Comment by daveres** [comment]
My query

[query_home_homemvc_home]
QueryIntervalSecs = 60
QueryIndices = <internalbalancer-*>
QueryJson = {
  "size": 0,
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "query": "domain: \"www.xxx.com\" AND request.raw: \"/\" AND ko:0",
          "analyze_wildcard": true
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gte": "now-1m",
                  "format": "epoch_millis"
                }
              }
            }
          ],
          "must_not": []
        }
      }
    }
  },
  "aggs": {
    "perc": {
      "percentiles": {
        "field": "reqtime",
        "percents": [
          50,
          95
        ]
      }
    }
  }
  }


Response:

{
  "took": 1104,
  "timed_out": false,
  "_shards": {
    "total": 1848,
    "successful": 1848,
    "failed": 0
  },
  "hits": {
    "total": 30,
    "max_score": 0,
    "hits": [

    ]
  },
  "aggregations": {
    "perc": {
      "values": {
        "50.0": 892.5,
        "95.0": 7145.99999999998
      }
    }
  }
}

Metric names:
* home_homemvc_home_perc_values_50**.**0
* home_homemvc_home_perc_values_95**.**0

**Comment by daveres** [comment]
I have just made a patch in /prometheus_client/core.py to replace ".0" to "" and it works

**Comment by Braedon** [comment]
Thanks for raising this @daveres, I'll try and release a patch in the next day or two. It will (probably) replace `.` (and maybe other disallowed characters?) with `_` in generated metric names.

**Comment by Braedon** [comment]
PR https://github.com/Braedon/prometheus-es-exporter/pull/4

**Comment by Braedon** [comment]
@daveres I've released 0.1.2 which should resolve this issue.
