### ISSUE TITLE
Aggregate by two labels

### ISSUE THREAD

**Issue by Martinmorrongiellomrf** [braedon/prometheus-es-exporter#31]
Hi,
We want to export using two labels of a metric and get the result like this:

> Metric :
> ins_lighthouse {uri="tenant.com", metric="performance"} 100.0
> ins_lighthouse {uri="tenant.com", metric="seo"} 100.0

instead of the current result that is:

> ins_lighthouse_seo{uri="tenant.com"} 100.0
>ins_lighthouse_performance{uri="tenant.com"} 100.0

Is there a way to get this result ? Some work in progress? If not maybe we will try to develop some code that could get this.

Thanks

**Comment by ntavares** [comment]
Hi @Martinmorrongiellomrf check this article: https://kuther.net/blog/prometheus-run-queries-against-elasticsearch-and-turn-it-metrics-and-alerts

Wouldn't that solve your problem?

**Comment by braedon** [comment]
Hi @Martinmorrongiellomrf, if the documents you're querying all have both `uri` and `metric` fields, you can simply use a single query with nested terms aggregations. e.g. first aggregate by `uri`, then have a nested aggregation on `metric`. This will produce metrics with both labels.

The `test_nested_terms` test in `tests.test_parser.py` has an example of this kind of query.
