### ISSUE TITLE
Add helm chart

### ISSUE THREAD

**Issue by alexppg** [braedon/prometheus-es-exporter#32]
Hi

Just FYI, I've made a prometheus-es-exporter helm chart, since it seems there wasn't one. I've made a [MR](https://github.com/helm/charts/pull/11871) to the official charts repository.

Thanks for your work!

**Comment by braedon** [comment]
Hi @alexppg, sorry it's taken so long to get this sorted.

I've finally got a [helm repo](https://braedon.github.io/helm/) up, with a [chart for prometheus-es-exporter](https://braedon.github.io/helm/prometheus-es-exporter/) based on your work. You can find the [chart source code here](https://github.com/braedon/braedon.github.io/tree/master/helm/prometheus-es-exporter).

I've pushed version `0.1.0` of the chart. Let me know if you have any issues with it. Please [raise an issue here](https://github.com/braedon/braedon.github.io/issues) if you run into problems. Thanks!
