### ISSUE TITLE
Support for client-certs?

### ISSUE THREAD

**Issue by sehdorn** [braedon/prometheus-es-exporter#39]
Hi,
how can i provide my client-cert / key to the application? I just see a parameter for a ca-cert, but not for a client-cert and its key.

thx

**Comment by jayanra** [comment]
How can i pass a ca.crt to the exporter. is there a docker variable?

**Comment by braedon** [comment]
@jayanra I've moved your question to its own issue - https://github.com/braedon/prometheus-es-exporter/issues/48

**Comment by braedon** [comment]
Support added in [0.6.0](https://github.com/braedon/prometheus-es-exporter/releases/tag/0.6.0)
