### ISSUE TITLE
Arbitrary labels for metrics

### ISSUE THREAD

**Issue by diversario** [braedon/prometheus-es-exporter#47]
I'm using this exporter to alert via Prometheus when a query hit count is over a certain limit. When an alert is triggered, the content of the alert is fairly basic, only telling the user the name of the alert and not much else. What I would like to do is to include a link to Kibana with the search that triggered the alert. E.g. the alert would look something like

```
Alert: App error(s) seen in the last 5 minutes - critical
 Cluster:  https://my-cluster
 Graph: <link to Prometheus graph>
 Details:
    • alertname: AppErrors
    ...
    • query: <link to Kibana search using this query>
```

Is that something this exporter supports?

**Comment by braedon** [comment]
Hi @diversario,

If I understand your question correctly, the functionality you're after lies in Prometheus/Alertmanager, not this exporter. Exporters just provide the base metrics - its up to your Prometheus and Alertmanager configs to convert those metrics into alerts, and format those alerts.

I've set up similar alerts to what you're wanting by templating out the text and links in the annotations of the [Prometheus alert config](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/), and then [configuring Alertmanager](https://prometheus.io/docs/alerting/configuration/) to use the annotations in the appropriate part of the notifications.

Let me know if that answers your question!
