### ISSUE TITLE
Support Elastic Scroll API

### ISSUE THREAD

**Issue by MartinRoenneburg** [braedon/prometheus-es-exporter#49]
Hi, 

I have a use case where I get thousands of results.

Actually I use a workaround with multiple queries which is not so cool...

Is there a possibility to query elastic using the scroll api ?

**Comment by braedon** [comment]
Hi @MartinRoenneburg,

This exporter focuses on exporting metrics from aggregations on documents, not documents themselves (though it does export the total count of matching documents). Extracting metrics from documents directly is considerably more complex a number of reasons, including how to handle scrolling, and how to define what metrics should be extracted (and how) from arbitrary documents.

Perhaps your use case can be achieved using aggregations? I'm happy to help with that if you can share a bit more about the use case.

Braedon
