### ISSUE TITLE
Error in parsing aggregated response

### ISSUE THREAD

**Issue by puthrichard** [braedon/prometheus-es-exporter#52]
I'm currently working on a big query containing aggregated values. I'm only interested in aggregations.1.value, which in this case would be 396.

The following is the response I get after running the query in ES (v7.3.0)
```
{
  "took" : 17509,
  "timed_out" : false,
  "_shards" : {
    "total" : 304,
    "successful" : 304,
    "skipped" : 290,
    "failed" : 0
  },
  "_clusters" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "1" : {
      "value" : 396
    }
  }
}
```

Here is the error message I am getting in return 
```
Traceback (most recent call last):
  File "/usr/src/app/prometheus_es_exporter/__init__.py", line 117, in run_query
    metrics = parse_response(response, [name])
  File "/usr/src/app/prometheus_es_exporter/parser.py", line 86, in parse_response
    total = response['hits']['total']
KeyError: 'total'
```

Thanks for getting back!

**Comment by braedon** [comment]
Hi @puthrichard, sorry you're having issues.

I can't immediately see how the code would produce that key error with that response. My best guess is that the exporter is getting a different response for some reason - possibly some kind of error that's not being handled.

Are you able to run the exporter locally, and add a logging line to the code? If so, please modify the `run_query()` function in `prometheus_es_exporter/__init__.py` as follows:
```
def run_query(es_client, name, indices, query, timeout):
    try:
        response = es_client.search(index=indices, body=query, request_timeout=timeout)

        logging.info('Received response %s', response)  # Add this line

        metrics = parse_response(response, [name])
...
```

That should log the full response from Elasticsearch. If you could then send me the log output for the response that causes the failure, hopefully I can isolate the issue!
