### ISSUE TITLE
How to user your code?

### ISSUE THREAD

**Issue by jinhang** [Braedon/prometheus-es-exporter#6]
could you give me an example to use your code?thanks !

**Comment by Braedon** [comment]
Hi @jinhang,

The [README.md](https://github.com/Braedon/prometheus-es-exporter/blob/master/README.md) shows how to install and run the app, [exporter.cfg](https://github.com/Braedon/prometheus-es-exporter/blob/master/exporter.cfg) has simple example queries, and the [parser tests](https://github.com/Braedon/prometheus-es-exporter/blob/master/tests/test_parser.py) have some more complicated query examples.

If anything isn't clear, or you are having issues with any specific part, let me know and I'll be happy to help.

Braedon

**Comment by jinhang** [comment]
thanks,could your write a detailed  steps to me , the readme is not clear,I can not try it run,thank you

**Comment by Braedon** [comment]
I can't give more detailed instructions beyond what is in the README
without knowing what the issue is, sorry.

Please let me know what you are trying to do (install it, run it, write
queries, deploy somewhere, etc.) and where you are getting stuck, and I'll
try and help.

**Comment by jinhang** [comment]
how to use the code monitor my es node?

**Comment by Braedon** [comment]
@jinhang the README provides instructions for using this exporter. If you any _specific_ part is confusing, or does not work, feel free to raise an issue with details, or better yet, submit a PR to help improve it.

Note that, as described in the README, this exporter doesn't monitor ES nodes themselves - it monitors data within a ES cluster by running queries and exporting the results as metrics. If you are wanting to monitor the health of your es node/cluster, you'll want a different tool.
