### ISSUE TITLE
Enable loading all configuration options from a file.

### ISSUE THREAD

**Issue by RobertKirk** [braedon/prometheus-es-exporter#62]
Currently you can load options to do with queries from a file, but not all the command line options. I'd like to be able to specify those in a configuration file, so that file can be kept in a separate place. I'm planning to work on this issue, probably just by adding this https://pypi.org/project/click-config-file/ and testing it a bit.

**Comment by braedon** [comment]
Sounds good @RobertKirk, happy to review a PR

**Comment by RobertKirk** [comment]
Have created the PR.

**Comment by braedon** [comment]
Fixed in [0.9.0](https://github.com/braedon/prometheus-es-exporter/releases/tag/0.9.0)
