### ISSUE TITLE
_search just return 10000

### ISSUE THREAD

**Issue by searchgithub** [braedon/prometheus-es-exporter#64]
I try to use the search, when the number is above 10000, it just return 10000,

POST logstash*/_search?size=0
{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": """  xxx """,
            "analyze_wildcard": true
          }
        }
      ],
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gt": "now-10m",
              "lt": "now"
            }
          }
        }
      ]
    }
  } 
}

--return
{
  "took" : 74,
  "timed_out" : false,
  "_shards" : {
    "total" : 355,
    "successful" : 355,
    "skipped" : 331,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}

**Comment by searchgithub** [comment]
Does it has limitation? Is there any aggressive way to get the count number?

**Comment by braedon** [comment]
Hi @searchgithub, it looks like you're hitting the total hit limit that was [introduced in ES7](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#track-total-hits-10000-default).

You should be able to force ES to compute the full count by [setting `track_total_hits` to `true`](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-body.html#request-body-search-track-total-hits) in your query JSON.
