### ISSUE TITLE
Total field metric

### ISSUE THREAD

**Issue by jonny-wg2** [braedon/prometheus-es-exporter#66]
Do you have an example to create a prometheus metric out of the count of total fields? 

For example, under `management/kibana/index_patterns` you can see the total number of fields. I would like to create a prometheus metric so I can alert if there are 1000 fields or more.

**Comment by braedon** [comment]
Hi @jonny-wg2, unfortunately Elasticsearch doesn't seem to expose this number anywhere, and I'm not aware of any way to calculate it with a query.

It looks like the only feasible way to get it is to parse the `/_mappings` endpoint and count the number of fields for each index. I'll have a look at adding a collector to do that.

**Comment by jonny-wg2** [comment]
Awesome!! For more details, what I am trying to achieve is

curl -s -XGET elasticsearch.cluster.domain:80/logstash-xxx-2020.06.19/_mapping?pretty grep type | wc -l
1143

Also, would you be able to supper multiple indicies? Logstash-yyy and logstash-xxx ?

**Comment by braedon** [comment]
Released in version [0.10.0](https://github.com/braedon/prometheus-es-exporter/releases/tag/0.10.0)
