### ISSUE TITLE
Can I exclude the `python_*` and `es_*` metrics somehow?

### ISSUE THREAD

**Issue by chrissound** [braedon/prometheus-es-exporter#67]
Hello! Many thanks for making this project! 

I was wondering, if there is a was to configure this to exclude the `python_*` and `es_*` metrics - hence to only have metrics based on my "own" queries? I'm hoping this will increase the response time of entire metrics page.

**Comment by braedon** [comment]
Hi @chrissound, you can use the `--cluster-health-disable`, `--nodes-stats-disable`, and `--indices-stats-disable` flags to turn of the `es_*` metrics. These metrics are fetched from the ES API on the fly when `/metrics` is called, so are probably the cause of slow responses if your ES cluster is large. The `python_*` metrics can't be disabled (currently?) but shouldn't produce much of any overhead.

**Comment by chrissound** [comment]
Thank you! Works great and a lot quicker now.
