### ISSUE TITLE
Handle merging metric dict when query match metric value drops

### ISSUE THREAD

**Issue by nithyashree675** [braedon/prometheus-es-exporter#76]
When the matching query count in Elasticsearch drops to zero, the [merge_metric_dicts](https://github.com/braedon/prometheus-es-exporter/blob/master/prometheus_es_exporter/metrics.py#L134) function crashes at code [None.copy()](https://github.com/braedon/prometheus-es-exporter/blob/master/prometheus_es_exporter/metrics.py#L124). This behaviour continues to provide same metric value to the Prometheus scrapper which is annoying as prometheus-es-exporter has to be restarted to fetch right metrics

Error Logs:

```
Traceback (most recent call last):
File "/usr/src/app/prometheus_es_exporter/scheduler.py", line 16, in scheduled_run 
func(*args, **kwargs) 
File "/usr/src/app/prometheus_es_exporter/__init__.py", line 187, in run_query 
zero_missing=True) 
File "/usr/src/app/prometheus_es_exporter/metrics.py", line 164, in merge_metric_dicts 
in old_metric_dict.items() 
File "/usr/src/app/prometheus_es_exporter/metrics.py", line 163, in <dictcomp> 
for metric_name, (metric_doc, label_keys, old_value_dict)
File "/usr/src/app/prometheus_es_exporter/metrics.py", line 124, in merge_value_dicts
value_dict = new_value_dict.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

`
"filename": "scheduler.py", 
"funcName": "scheduled_run", 
"levelname": "ERROR", 
"levelno": 40, 
"lineno": 18, 
"log": "prometheus_es_exporter.scheduler.ERROR MainThread Error while running scheduled job."
"message": "Error while running scheduled job.", 
"message_format": "Error while running scheduled job.", 
"module": "scheduler", 
"name": "prometheus_es_exporter.scheduler", 
"pathname": "/usr/src/app/prometheus_es_exporter/scheduler.py", 
"process": 1, 
"processName": "MainProcess", 
"relativeCreated": 957360909.1424942, 
"thread": 140296627201856, 
"threadName": "MainThread"
`

**Comment by braedon** [comment]
Fixed in [0.11.2](https://github.com/braedon/prometheus-es-exporter/releases/tag/0.11.2)
