### ISSUE TITLE
Support Authorization: header for connection to ElasticSearch

### ISSUE THREAD

**Issue by rg2011** [braedon/prometheus-es-exporter#82]
First of all, thanks for sharing your code.

I would like to use it to perform queries against the log store of RedHat's Openshift, but Openshift places its ElasticSearch cluster behind an oAuth proxy that requires Bearer Authentication (please see [this](https://docs.openshift.com/container-platform/4.5/logging/config/cluster-logging-log-store.html#cluster-logging-elasticsearch-exposing_cluster-logging-store))

The Elasticsearch constructor supports an [additional parameter `headers`](https://elasticsearch-py.readthedocs.io/en/master/connection.html#elasticsearch.Urllib3HttpConnection), where we could add an `Authorization: Bearer ....` header. That would probably mean adding a new cli flag to provide the bearer token.

I'll try to submit a PR for this, if you agree.

**Comment by braedon** [comment]
Hi @rg2011, adding something similar to the basic-auth handling but for `Authorization: Bearer ...` sounds like a good idea. Happy to review a PR.

I assume the Openshift tokens are static/long-lived?

**Comment by rg2011** [comment]
Yes, as long as you use ServiceAccount tokens, they won't expire (https://docs.openshift.com/container-platform/4.5/authentication/using-service-accounts-in-applications.html). Let's see if I can make this work.

**Comment by braedon** [comment]
Released in [0.13.0](https://github.com/braedon/prometheus-es-exporter/releases/tag/0.13.0)
