### ISSUE TITLE
Composite aggregations

### ISSUE THREAD

**Issue by askz** [braedon/prometheus-es-exporter#88]
Hi, 
I have experimented with composite aggregation, since I need to extract context metrics for some alerts.

Here's is the aggregation: 
```json
"aggs": {
      "doc": {
        "composite": {
          "sources": [
            {
              "id": { "terms": { "field": "_id" } }
            },
            {
              "host": { "terms": { "field": "host.keyword" } }
            },
            {
              "method": { "terms" : { "script": { "source": "doc['0.req.method.keyword'].value" } } }
            },
            {
              "url": { "terms" : { "script": { "source": "(doc['0.req.originalUrl.keyword'].size() >= 1 ? doc['0.req.originalUrl.keyword'].value : doc['0.req.url.keyword'].value)" } } }
            },
            {
              "code": { "terms" : { "script": { "source": "doc['0.res.code'].value" } } }
            },
            {
              "type": { "terms" : { "script": { "source": "doc['0.res.type.keyword'].value" } } }
            }
          ]
        }
      }
    }
```

Here's what's returned: 
```
api_errors_doc_doc_count{doc="{'url': '/', 'host': 'api-2', 'method': 'GET', 'code': '12', 'id': 'b7LX1nUB31GzKhNCN3yK', 'type': 'USS_ERROR'}", instance="xxxxxx:9206", job="elc-1_ESExporter"}
```

the problem here is that doc is now a string....
is there a way to get these vars as labels?
Or another aggregation way to do this ? 

Thanks for your time and investment on this project!

**Comment by braedon** [comment]
I've added basic composite aggregation support in [0.14.0](https://github.com/braedon/prometheus-es-exporter/releases/tag/0.14.0).

I've only tested against fairly basic queries, but hopefully it covers your use case. If not, or if you run into other issues, don't hesitate to raise another issue with details and I'll see what I can do.

**Comment by askz** [comment]
wow that was really fast !!

Just tested and it fits perfectly my use case, many many thanks.
