### ISSUE TITLE
InsecureRequestWarning on secure request

### ISSUE THREAD

**Issue by askz** [braedon/prometheus-es-exporter#89]
I have my ES cluster behind HAProxy with SSL from Let's Encrypt.

Still, I get those warnings at every request.

```
Nov 18 21:03:10 elc-1 prometheus-es-exporter[4275]: [2020-11-18 21:03:10,155] elasticsearch.INFO Thread-62 GET https://xxxxxx:443/_nodes/stats [status:200 request:0.119s]
Nov 18 21:03:22 elc-1 prometheus-es-exporter[4275]: [2020-11-18 21:03:22,938] py.warnings.WARNING MainThread /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host xxxxxxx Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Nov 18 21:03:22 elc-1 prometheus-es-exporter[4275]:   InsecureRequestWarning,
```
Is there a possibility to actually check the certificate if it's not given in configuration?

**Comment by braedon** [comment]
Hi @askz, you'll need to provide the `--ca-certs` option, pointing to some set of CA certs.

The exporter doesn't (explicitly) ship with CA certs, as I'd then need to release a new docker image whenever the bundle is updated (and a lot of orgs need their own internal certs anyway).

As it happens, the docker image actually contains (at least) two CA cert bundles, which you can use to quickly get cert checking running (assuming you're using docker). However, these aren't explicit dependencies, so are certain to be out of date (or soon will be), and may disappear in the future.

OS certs:
```
--ca-certs='/etc/ssl/certs/ca-certificates.crt'
```

Python `certifi` package (based off Mozilla's bundle):
```
--ca-certs='/usr/local/lib/python3.8/site-packages/certifi/cacert.pem'
```

I strongly recommend using some other method of provisioning certs so you can ensure they're available and manage their update cycle. For example, you could extend the docker image to explicitly install the latest version of `certifi`.

**Comment by askz** [comment]
Thanks. 
Closing as it's resolved !
